/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TrafficLightState } from "./components/traffic-light/traffic-light-state";
import { TrafficLightColor } from "./components/traffic-light/traffic-light-color";
export namespace Components {
    interface TrafficLight {
        "color": TrafficLightColor;
        "currentState": TrafficLightState;
    }
}
declare global {
    interface HTMLTrafficLightElement extends Components.TrafficLight, HTMLStencilElement {
    }
    var HTMLTrafficLightElement: {
        prototype: HTMLTrafficLightElement;
        new (): HTMLTrafficLightElement;
    };
    interface HTMLElementTagNameMap {
        "traffic-light": HTMLTrafficLightElement;
    }
}
declare namespace LocalJSX {
    interface TrafficLight {
        "color"?: TrafficLightColor;
        "currentState"?: TrafficLightState;
    }
    interface IntrinsicElements {
        "traffic-light": TrafficLight;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "traffic-light": LocalJSX.TrafficLight & JSXBase.HTMLAttributes<HTMLTrafficLightElement>;
        }
    }
}
